services:
  - type: web
    name: java-project-99
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /welcome
    envVars:
      - key: JAVA_VERSION
        value: "21"
