spring:
  datasource:
    url: ${POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

sentry:
  dsn: https://9879e91df6dc602738d9ce0f48d8e278@o4511315299532800.ingest.de.sentry.io/4511315303465040
  send-default-pii: true